// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx4-5zMbl1qaxq1d09QjmvqtNTy806idE',
    appId: '1:137873750472:web:31a90c8c2f96750c2fa8fd',
    messagingSenderId: '137873750472',
    projectId: 'ecommers-d1bf7',
    authDomain: 'ecommers-d1bf7.firebaseapp.com',
    storageBucket: 'ecommers-d1bf7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWknBTekdWH4CFekWWKikgcddQxa7HG0Y',
    appId: '1:137873750472:android:29b8ca19bfc4dc4b2fa8fd',
    messagingSenderId: '137873750472',
    projectId: 'ecommers-d1bf7',
    storageBucket: 'ecommers-d1bf7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmVoWkQ_NoHVovlqoBBCXBDXbx-xZoSO0',
    appId: '1:137873750472:ios:f40d322e7f4fb0532fa8fd',
    messagingSenderId: '137873750472',
    projectId: 'ecommers-d1bf7',
    storageBucket: 'ecommers-d1bf7.appspot.com',
    androidClientId: '137873750472-ah5t0ol6dhi9ucdmqiok0gbn7tgprjbi.apps.googleusercontent.com',
    iosClientId: '137873750472-50vuujcngshiforv8tevtldmitiv3n5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

}